# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_json_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Seattle', max_length=255),
            preserve_default=False,
        ),
    ]
