# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_json_finder', '0002_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
